CREATE SEQUENCE SEQ_PAUTA
				START WITH 100
				INCREMENT BY 1
				NO MINVALUE
				NO MAXVALUE
				CACHE 1;;

CREATE TABLE PAUTA (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('SEQ_PAUTA'::REGCLASS) PRIMARY KEY,
	TITULO VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	CREATED TIMESTAMP,
	UPDATED TIMESTAMP,
	DELETED TIMESTAMP,
	STATUS VARCHAR(255) NOT NULL,
	EXPIRACAO TIMESTAMP
);

CREATE SEQUENCE SEQ_ASSOCIADO
				START WITH 100
				INCREMENT BY 1
				NO MINVALUE
				NO MAXVALUE
				CACHE 1;;

CREATE TABLE ASSOCIADO (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('SEQ_ASSOCIADO'::REGCLASS) PRIMARY KEY,
	CPF VARCHAR(255) NOT NULL,
	VOTO VARCHAR(255),
	CREATED TIMESTAMP,
	UPDATED TIMESTAMP,
	DELETED TIMESTAMP
);

CREATE TABLE PAUTA_ASSOCIADO (
	ASSOCIADO_ID BIGINT NOT NULL REFERENCES PAUTA(ID),
	PAUTA_ID BIGINT NOT NULL REFERENCES ASSOCIADO(ID)
);